// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcMxaJ7JqHFI-JLQnaI420M5GZ9fDYTV4',
    appId: '1:804746209774:web:4ee45afd8ff8477c0b86ff',
    messagingSenderId: '804746209774',
    projectId: 'blsa-e25b5',
    authDomain: 'blsa-e25b5.firebaseapp.com',
    storageBucket: 'blsa-e25b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrlO7SkKAnNWRT9XXe2uT_vyYNCu0TAp8',
    appId: '1:804746209774:android:5d9c9e897d1b98f40b86ff',
    messagingSenderId: '804746209774',
    projectId: 'blsa-e25b5',
    storageBucket: 'blsa-e25b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9pBqEXt8vCLoe0-XzSVCRkcyI5Zy1L_8',
    appId: '1:804746209774:ios:510413dc4d789f270b86ff',
    messagingSenderId: '804746209774',
    projectId: 'blsa-e25b5',
    storageBucket: 'blsa-e25b5.appspot.com',
    androidClientId: '804746209774-ivk4n1qfg60cnejvs0j5fd4ha33ardpk.apps.googleusercontent.com',
    iosClientId: '804746209774-86kg2h6ov0gm1po4uju735rlhhen0gks.apps.googleusercontent.com',
    iosBundleId: 'com.example.bls',
  );
}
